                                                                                       <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
																						   <ItemGroup>
																							   <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
																								   <PrivateAssets>all</PrivateAssets>
																								   <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
																							   </PackageReference>
																							   <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
																								   <PrivateAssets>all</PrivateAssets>
																								   <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
																							   </PackageReference>
																							   <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
																						   </ItemGroup>

  <ItemGroup>
    <Folder Include="Auth\" />
    <Folder Include="Repositories\" />
    <Folder Include="Persistence\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NovaMartPOS.Domain\NovaMartPOS.Domain.csproj" />
    <ProjectReference Include="..\NovaMartPOS.Application\NovaMartPOS.Application.csproj" />
  </ItemGroup>

</Project>
